In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [3]:
# 1. 导入工具包
import numpy as np
import pandas as pd
from collections import Counter

# 2. 欧式距离定义
def euclidean_distance(vec1,vec2):
    return np.sqrt(np.sum(np.square(vec1 - vec2)))
    
# 3. 构造数据集  
train_data = {'宝贝当家':[45,2,9,'喜剧片'],
              '美人鱼':[21,17,5,'喜剧片'],
              '澳门风云3':[54,9,11,'喜剧片'],
              '功夫熊猫3':[39,0,31,'喜剧片'],
              '谍影重重':[5,2,57,'动作片'],
              '叶问3':[3,2,65,'动作片'],
              '我的特工爷爷':[6,4,21,'动作片'],
              '奔爱':[7,46,4,'爱情片'],
              '夜孔雀':[9,39,8,'爱情片'],
              '代理情人':[9,38,2,'爱情片'],
              '新步步惊心':[8,34,17,'爱情片'],
              '伦敦陷落':[2,3,55,'动作片']
              }

train_df = pd.DataFrame(train_data).T
train_df.columns = ['搞笑镜头','拥抱镜头','打斗镜头','电影类型']

test_data = {'唐人街探案':[23,3,17]} 

# 4. 确定K值和分类的电影
K = 5
movie = '唐人街探案'

# 5. 计算欧式距离
distance_list = []
for train_X in train_df.values[:,:-1]:
    test_X = np.array(test_data[movie])
    distance_list.append(euclidean_distance(train_X,test_X))
    
# 6. 按照距离递增排序
distance_df = pd.DataFrame({"欧式距离":distance_list},index=train_df.index)
result = pd.concat([train_df,distance_df],axis=1).sort_values(by="欧式距离")

# 7. ToDo：输出分类结果
d = Counter(result.head(K)['电影类型'])
print(movie,max(d,key=d.get))

唐人街探案 喜剧片

In [10]:
result

       搞笑镜头 拥抱镜头 打斗镜头 电影类型       欧式距离
我的特工爷爷    6    4   21  动作片  17.492856
美人鱼      21   17    5  喜剧片  18.547237
功夫熊猫3    39    0   31  喜剧片  21.470911
宝贝当家     45    2    9  喜剧片  23.430749
澳门风云3    54    9   11  喜剧片  32.140317
新步步惊心     8   34   17  爱情片  34.438351
夜孔雀       9   39    8  爱情片  39.661064
代理情人      9   38    2  爱情片  40.570926
伦敦陷落      2    3   55  动作片  43.416587
谍影重重      5    2   57  动作片  43.874822
奔爱        7   46    4  爱情片  47.686476
叶问3       3    2   65  动作片  52.009614

In [11]:
d

Counter({'动作片': 1, '喜剧片': 4})

In [12]:
max(d,key=d.get)

'喜剧片'

In [4]:
train_data

{'宝贝当家': [45, 2, 9, '喜剧片'],
 '美人鱼': [21, 17, 5, '喜剧片'],
 '澳门风云3': [54, 9, 11, '喜剧片'],
 '功夫熊猫3': [39, 0, 31, '喜剧片'],
 '谍影重重': [5, 2, 57, '动作片'],
 '叶问3': [3, 2, 65, '动作片'],
 '我的特工爷爷': [6, 4, 21, '动作片'],
 '奔爱': [7, 46, 4, '爱情片'],
 '夜孔雀': [9, 39, 8, '爱情片'],
 '代理情人': [9, 38, 2, '爱情片'],
 '新步步惊心': [8, 34, 17, '爱情片'],
 '伦敦陷落': [2, 3, 55, '动作片']}

In [6]:
train_df

       搞笑镜头 拥抱镜头 打斗镜头 电影类型
宝贝当家     45    2    9  喜剧片
美人鱼      21   17    5  喜剧片
澳门风云3    54    9   11  喜剧片
功夫熊猫3    39    0   31  喜剧片
谍影重重      5    2   57  动作片
叶问3       3    2   65  动作片
我的特工爷爷    6    4   21  动作片
奔爱        7   46    4  爱情片
夜孔雀       9   39    8  爱情片
代理情人      9   38    2  爱情片
新步步惊心     8   34   17  爱情片
伦敦陷落      2    3   55  动作片

In [7]:
train_df.values

array([[45, 2, 9, '喜剧片'],
       [21, 17, 5, '喜剧片'],
       [54, 9, 11, '喜剧片'],
       [39, 0, 31, '喜剧片'],
       [5, 2, 57, '动作片'],
       [3, 2, 65, '动作片'],
       [6, 4, 21, '动作片'],
       [7, 46, 4, '爱情片'],
       [9, 39, 8, '爱情片'],
       [9, 38, 2, '爱情片'],
       [8, 34, 17, '爱情片'],
       [2, 3, 55, '动作片']], dtype=object)

In [9]:
train_df.values[:,:-1]

array([[45, 2, 9],
       [21, 17, 5],
       [54, 9, 11],
       [39, 0, 31],
       [5, 2, 57],
       [3, 2, 65],
       [6, 4, 21],
       [7, 46, 4],
       [9, 39, 8],
       [9, 38, 2],
       [8, 34, 17],
       [2, 3, 55]], dtype=object)

In [5]:
test_data

{'唐人街探案': [23, 3, 17]}